const fs=require('fs'),path=require('path');
const {pathToFileURL}=require('url');
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
(async()=>{
 const {marked}=await import(pathToFileURL(require.resolve('marked')).href);
 const base=__dirname;
 const sheets=[['ДОСЬЕ_СТРАТЕГИЯ_И_ДЕРЕВО_СОБЫТИЙ.md','ДОСЬЕ.html','Досье для независимого адвокатского аудита'],['КАТАЛОГ_ИСТОЧНИКОВ.md','КАТАЛОГ_ИСТОЧНИКОВ.html','Источники и проекты для проверки']];
 for(const [src,dst,title] of sheets){
   const md=fs.readFileSync(path.join(base,src),'utf8');
   const toc=[],branches=[],used=new Set();let seq=0;
   let html=marked.parse(md,{gfm:true});
   html=html.replace(/<h([1-6])>([\s\S]*?)<\/h\1>/g,(all,level,inner)=>{
     const plain=inner.replace(/<[^>]+>/g,'').replaceAll('&amp;','&');
     let id=plain.match(/^([BC]\d{2})\b/)?.[1]?.toLowerCase()||('s'+(plain.match(/^(\d+(?:\.\d+)*)\s/)?.[1]?.replaceAll('.','-')||++seq));
     while(used.has(id))id+='x';used.add(id);
     if(level==='2')toc.push({id,text:plain});
     if(/^B\d{2}\b/.test(plain))branches.push({id,text:plain});
     if(level==='1')return '';
     return `<h${level} id="${id}">${inner}</h${level}>`;
   });
   html=html.replaceAll('<table>','<div class="table-wrap"><table>').replaceAll('</table>','</table></div>');
   const words=md.split(/\s+/).filter(Boolean).length;
   const nav=toc.map(x=>`<a href="#${x.id}">${esc(x.text)}</a>`).join('');
   const jump=branches.length?`<label for="branch">Перейти к ветви</label><select id="branch"><option value="">Выберите событие</option>${branches.map(x=>`<option value="${x.id}">${esc(x.text)}</option>`).join('')}</select>`:'';
   const full=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · 02.10.2026</title><style>
   :root{--ink:#233240;--muted:#596b7b;--blue:#174c70;--line:#d6e1e9;--paper:#f4f7f9}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.7 'Segoe UI',Arial,sans-serif}a{color:#165b83;text-underline-offset:3px}header{background:#173b52;color:white;padding:34px max(24px,calc((100vw - 1360px)/2));}header h1{font-size:33px;line-height:1.2;max-width:1000px;margin:10px 0 15px}header p{max-width:1050px;color:#d9e5ed;font-size:15px}.eyebrow{font-size:12px;color:#bdcfdb;letter-spacing:1px;text-transform:uppercase}.toplinks{display:flex;gap:14px;flex-wrap:wrap;margin-top:18px}.toplinks a{color:#fff;border:1px solid #ffffff50;padding:6px 12px;border-radius:6px;text-decoration:none;font-size:13px}.layout{max-width:1410px;margin:0 auto;display:grid;grid-template-columns:285px minmax(0,1fr);gap:25px;padding:25px}.sidebar{position:sticky;top:16px;align-self:start;max-height:calc(100vh - 35px);overflow:auto;background:#fff;border:1px solid var(--line);border-radius:10px;padding:16px;font-size:13px}.sidebar strong{display:block;margin-bottom:12px}.sidebar nav a{display:block;margin:0 0 10px;line-height:1.45;text-decoration:none}.sidebar label{display:block;margin:14px 0 5px;font-weight:600}.sidebar select{max-width:100%;width:100%;padding:7px;border:1px solid var(--line);background:white;font:inherit}article{min-width:0;background:white;border:1px solid var(--line);border-radius:11px;padding:25px 30px 40px}h2{font-size:25px;line-height:1.3;margin:35px 0 16px;scroll-margin-top:20px;color:#173b52}h2:first-child{margin-top:0}h3{font-size:19px;line-height:1.4;margin:25px 0 10px;scroll-margin-top:20px}h3[id^=b]{padding-top:13px;border-top:1px solid var(--line)}p{margin:10px 0 16px}li{margin:7px 0}code{font-size:13px;background:#eef3f6;padding:1px 5px;word-break:break-word}.table-wrap{overflow-x:auto;margin:18px 0}table{border-collapse:collapse;width:100%;font-size:14px;min-width:650px}th,td{border:1px solid var(--line);padding:10px 12px;text-align:left;vertical-align:top}th{background:#eaf0f5;color:#193d56}blockquote{border-left:4px solid #8a641d;background:#fff5e5;margin:16px 0;padding:10px 18px}.notice{background:#fff5e5;border-left:5px solid #a87921;padding:15px 18px;margin:0 0 24px;font-size:14px}.muted{color:var(--muted);font-size:13px}footer{max-width:1400px;margin:auto;padding:0 25px 35px;font-size:13px;color:var(--muted)}
   @media(max-width:950px){.layout{grid-template-columns:1fr;padding:14px;gap:14px}.sidebar{position:static;max-height:none}.sidebar nav{display:grid;grid-template-columns:1fr 1fr;gap:5px 15px}.sidebar details:not([open]) nav{display:none}article{padding:20px}header{padding:26px 20px}header h1{font-size:28px}}@media(max-width:540px){.sidebar nav{grid-template-columns:1fr}article{padding:17px}h2{font-size:22px}h3{font-size:18px}}
   @media print{body{background:white;font-size:10.5pt}header{background:white;color:#111;padding:0 0 15px}header p,.eyebrow{color:#333}.toplinks,.sidebar{display:none}.layout{display:block;padding:0}article{border:0;padding:0}.table-wrap{overflow:visible}table{min-width:0;font-size:9pt}tr{break-inside:avoid}h2,h3{break-after:avoid}.notice{background:white;border:1px solid #aaa}a{color:#111}footer{padding:15px 0}}
   </style></head><body><header><div class="eyebrow">Справа 127/20805/26 · внутренний материал · 02 октября 2026</div><h1>${esc(title)}</h1><p>Приоритет клиента — максимально возможное законное время до решения при почти отсутствующих средствах. Основания, контраргументы, расходы и пределы проверяются раздельно. Желаемый год не является обещанным сроком суда.</p><div class="toplinks"><a href="ДОСЬЕ.html">Основное досье</a><a href="КАТАЛОГ_ИСТОЧНИКОВ.html">Источники</a><a href="drafts/roadmap.html">Проекты документов</a><a href="${encodeURI(src)}">Редактируемый Markdown</a></div></header><div class="layout"><aside class="sidebar"><strong>Навигация</strong><details open><summary>Оглавление</summary><nav>${nav}</nav></details>${jump}<p class="muted">${branches.length?`${branches.length} ветвей · `:''}Поиск по тексту: Ctrl+F.<br>Сначала удобно читать разделы 1, 4–7 и 17.</p></aside><article><div class="notice"><strong>Для клиента и независимого проверяющего адвоката.</strong> Не направлять этот документ или весь архив суду/банку. Независимый аудит ещё не выполнен; ответ банка отсутствует, отдельные процессуальные статусы неизвестны.</div>${html}</article></div><footer>Исходные PDF в этой фазе повторно не анализировались. Тексты и первичные файлы связаны в каталоге; контрольные суммы — в manifest.json. Личного ключа КЭП в подборке нет. Подача документов и внешняя передача не выполнялись.</footer><script>document.getElementById('branch')?.addEventListener('change',e=>{if(e.target.value)location.hash=e.target.value});</script></body></html>`;
   fs.writeFileSync(path.join(base,dst),full,'utf8');
   console.log(JSON.stringify({file:dst,words,sections:toc.length,branches:branches.length}));
 }
})().catch(e=>{console.error(String(e));process.exitCode=1});
